quiet: False  # не выводить предупреждения
disable-version-string: True  # отключает генерацию версионных строк
with-expecter: True # генерировать expecter, рекомендовано включить
mockname: "{{.InterfaceName}}"  # имя сгенерированного интерфейса
filename: "{{.MockName}}.go"  # имя файла
outpkg: mocks # пакет со сгенерированными интерфейсами
tags: "custom1"
packages:
  github.com/arslanovdi/logistic-package-api:
    config:
      keeptree: True  # сохранять дерево папок при генерации, полезно если есть интерфейсы с одинаковыми именами в разных пакетах
    interfaces:
      EventRepo:
      EventSender:
