quiet: False  # не выводить предупреждения
disable-version-string: True  # отключает генерацию версионных строк
with-expecter: True # генерировать expecter, рекомендовано включить
dir: "mocks/"
mockname: "{{.InterfaceName}}"  # имя сгенерированного интерфейса
filename: "{{.MockName}}.go"  # имя файла
outpkg: mocks # пакет со сгенерированными интерфейсами
tags: "custom1"
packages:
  github.com/arslanovdi/logistic-package-api/internal/outbox/repo:
    interfaces:
      EventRepo:
  github.com/arslanovdi/logistic-package-api/internal/outbox/sender:
    interfaces:
      EventSender:
